// Demo data for trying every CareFirst workflow by hand — `npm run seed`.
//
// WIPES the database in MONGO_URI (from .env) and the uploaded / cached files,
// then creates accounts and records in every interesting state. Dates are
// relative to "now", so the data stays fresh whenever you re-run it.
// All demo users share one password; the admin uses ADMIN_USERNAME / ADMIN_PASSWORD.

require('dotenv').config();
const fs       = require('fs');
const path     = require('path');
const mongoose = require('mongoose');

const User                 = require('../models/User');
const PatientProfile       = require('../models/PatientProfile');
const DoctorProfile        = require('../models/DoctorProfile');
const LabProfile           = require('../models/LabProfile');
const LawyerProfile        = require('../models/LawyerProfile');
const Wallet               = require('../models/Wallet');
const DefaulterCase        = require('../models/DefaulterCase');
const Appointment          = require('../models/Appointment');
const LabBooking           = require('../models/LabBooking');
const Prescription         = require('../models/Prescription');
const TestReport           = require('../models/TestReport');
const CommunityApplication = require('../models/CommunityApplication');
const Notification         = require('../models/Notification');

const { fileUrl } = require('../utils/fileUrl');
const { planAmounts, buildSchedule } = require('../utils/installmentPlan');
const { pktDate, addDays, weekdayOf, pktInstant } = require('../utils/schedule');
const {
  generateInstallmentAgreement, generateInstallmentAgreementUrdu, generateLegalAgreement,
} = require('../utils/legalAgreementTemplate');
const { SERVICE_FEE, GRACE_DAYS } = require('../config/installments');
const { AUDIO_DIR } = require('../config/azure');
const { CNIC_DIR } = require('../middleware/upload');

const PASSWORD = 'password123';
const DAY = 24 * 60 * 60 * 1000;
const now = new Date();
const daysAgo = (n) => new Date(now.getTime() - n * DAY);
const today = pktDate(now);

if (!process.argv.includes('--reset')) {
  console.error('This wipes the database and uploads. Run: npm run seed  (or node scripts/seed.js --reset)');
  process.exit(1);
}
if (process.env.NODE_ENV === 'production') {
  console.error('Refusing to seed with NODE_ENV=production');
  process.exit(1);
}

// ─── Files ────────────────────────────────────────────────────────────────────
const UPLOADS = path.join(__dirname, '..', 'uploads');

// A small one-page PDF with a few lines of text (receipts, reports, documents)
const pdf = (title, lines) => {
  const esc = (s) => s.replace(/[\\()]/g, c => `\\${c}`);
  const text = [`BT /F1 20 Tf 60 770 Td (${esc(title)}) Tj ET`]
    .concat(lines.map((l, i) => `BT /F1 12 Tf 60 ${730 - i * 22} Td (${esc(l)}) Tj ET`))
    .concat([`BT /F1 9 Tf 60 60 Td (${esc('CareFirst demo document - generated by scripts/seed.js')}) Tj ET`])
    .join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${Buffer.byteLength(text)} >>\nstream\n${text}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let out = '%PDF-1.4\n';
  const offsets = objects.map((obj, i) => { const at = Buffer.byteLength(out); out += `${i + 1} 0 obj\n${obj}\nendobj\n`; return at; });
  const xref = Buffer.byteLength(out);
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.map(o => `${String(o).padStart(10, '0')} 00000 n \n`).join('')}`;
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return out;
};

let fileCount = 0;
const saveFile = (folder, title, lines) => {
  fs.mkdirSync(path.join(UPLOADS, folder), { recursive: true });
  const name = `seed-${++fileCount}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}.pdf`;
  fs.writeFileSync(path.join(UPLOADS, folder, name), pdf(title, lines));
  return fileUrl(folder, name);
};
const receipt = (who, what, amount, to) =>
  saveFile('receipts', `Payment receipt - ${what}`, [`Paid by: ${who}`, `Paid to: ${to}`, `Amount: PKR ${amount.toLocaleString('en-US')}`, `Date: ${today}`, 'Reference: DEMO-' + Math.floor(Math.random() * 1e6)]);

// A clearly fake CNIC card picture (PNG) in the private CNIC folder → file name
const cnicCard = async (name, cnic, side, address) => {
  const sharp = require('sharp');
  const esc = (t) => String(t).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const lines = side === 'front'
    ? [['Name', name], ['Identity Number', cnic], ['Country of Stay', 'Pakistan']]
    : [['Address', address || '—'], ['Identity Number', cnic]];
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400">
    <rect width="640" height="400" rx="24" fill="#e8f3ec"/>
    <rect x="0" y="0" width="640" height="70" rx="24" fill="#1f6f43"/>
    <text x="28" y="45" font-family="Arial" font-size="24" font-weight="bold" fill="#fff">PAKISTAN · NATIONAL IDENTITY CARD (${side.toUpperCase()})</text>
    ${side === 'front' ? '<rect x="470" y="100" width="140" height="170" rx="10" fill="#c9d8cf"/><circle cx="540" cy="160" r="38" fill="#a9bdb1"/><rect x="495" y="205" width="90" height="50" rx="25" fill="#a9bdb1"/>' : ''}
    ${lines.map(([label, value], i) => `<text x="32" y="${120 + i * 70}" font-family="Arial" font-size="16" fill="#4b6355">${esc(label)}</text>
    <text x="32" y="${146 + i * 70}" font-family="Arial" font-size="24" font-weight="bold" fill="#10251a">${esc(value)}</text>`).join('')}
    <text x="320" y="370" text-anchor="middle" font-family="Arial" font-size="20" font-weight="bold" fill="#c9372c">DEMO PICTURE — NOT A REAL CNIC</text>
  </svg>`;
  fs.mkdirSync(CNIC_DIR, { recursive: true });
  const file = `seed-${++fileCount}-cnic-${cnic.replace(/\D/g, '')}-${side}.png`;
  await sharp(Buffer.from(svg)).png().toFile(path.join(CNIC_DIR, file));
  return file;
};

const clearFolder = (dir) => {
  if (!fs.existsSync(dir)) return 0;
  let n = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) n += clearFolder(p);
    else { fs.unlinkSync(p); n++; }
  }
  return n;
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
const users = {};
const createUser = async (key, data) => {
  users[key] = await User.create({ password: PASSWORD, status: 'active', ...data });
  return users[key];
};

const notify = (recipient, type, title, message, meta = {}) =>
  Notification.create({ recipient: recipient._id || recipient, type, title, message, meta });

// Next date (from `fromOffset` days ahead) whose weekday is in `days`
const nextDateOn = (days, fromOffset = 0) => {
  for (let i = fromOffset; i < fromOffset + 14; i++) {
    const d = addDays(today, i);
    if (days.includes(weekdayOf(d))) return d;
  }
  return addDays(today, fromOffset);
};

// An appointment at a real instant (date/time in PKT)
const appointment = async ({ patient, doctor, startsAt, status = 'confirmed', fee, duration, ...rest }) => {
  const pkt = new Date(startsAt.getTime() + 5 * 3600 * 1000);
  return Appointment.create({
    patient: patient._id, doctor: doctor._id,
    date: pkt.toISOString().slice(0, 10), time: pkt.toISOString().slice(11, 16),
    startsAt, durationMinutes: duration, fee, status, ...rest,
  });
};

// An installment plan exactly as the app would create it, in the requested state
const makePlan = async ({ patientKey, labKey, testName, guarantor, state, approvedDaysAgo = 1, activatedDaysAgo }) => {
  const patient = users[patientKey];
  const profile = await PatientProfile.findOne({ user: patient._id });
  const labProfile = await LabProfile.findOne({ user: users[labKey]._id });
  const test = labProfile.tests.find(t => t.name === testName);
  const total = Math.round(test.price);
  const { downPayment, installments } = planAmounts(total, test.installmentCount);

  const input = {
    patient, patientCnic: profile.cnic, patientAddress: profile.address, guarantor, labName: labProfile.labName, testName: test.name,
    totalAmount: total, downPayment, installments, tenureDays: test.installmentTenureDays,
    serviceFee: SERVICE_FEE, graceDays: GRACE_DAYS,
  };
  const wallet = new Wallet({
    patient: patient._id, lab: users[labKey]._id, labTest: test._id, testName: test.name,
    totalAmount: total, installmentCount: installments.length, installmentTenureDays: test.installmentTenureDays,
    downPayment: { amount: downPayment }, serviceFee: { amount: SERVICE_FEE },
    patientCnic: profile.cnic, patientAddress: profile.address, guarantor,
    cnicPictures: {
      patientFront:   await cnicCard(patient.name, profile.cnic, 'front'),
      patientBack:    await cnicCard(patient.name, profile.cnic, 'back', profile.address),
      guarantorFront: await cnicCard(guarantor.name, guarantor.cnic, 'front'),
      guarantorBack:  await cnicCard(guarantor.name, guarantor.cnic, 'back', guarantor.address),
    },
    agreement: { text: generateInstallmentAgreement(input), textUrdu: generateInstallmentAgreementUrdu(input), acceptedAt: daysAgo(approvedDaysAgo + 1) },
    status: 'pending_approval',
  });

  if (state !== 'pending_approval') {
    wallet.status = 'awaiting_fee';
    wallet.planApprovedAt = daysAgo(approvedDaysAgo);
    wallet.planApprovedBy = users.admin._id;
  }
  if (activatedDaysAgo !== undefined) {
    const activatedAt = daysAgo(activatedDaysAgo);
    wallet.serviceFee.receiptUrl = receipt(patient.name, 'CareFirst service fee', SERVICE_FEE, 'CareFirst');
    wallet.serviceFee.receiptUploadedAt = activatedAt;
    wallet.serviceFee.adminVerified = true;
    wallet.serviceFee.adminVerifiedAt = activatedAt;
    wallet.serviceFee.adminVerifiedBy = users.admin._id;
    wallet.installments = buildSchedule(installments, test.installmentTenureDays, activatedAt);
    wallet.activatedAt = activatedAt;
    wallet.status = 'active';
  }
  return { wallet, labProfile, test };
};

// ─── Seed ─────────────────────────────────────────────────────────────────────
const seed = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  const dbName = mongoose.connection.db.databaseName;
  console.log(`Resetting database "${dbName}"…`);
  await mongoose.connection.dropDatabase();
  for (const model of Object.values(mongoose.models)) await model.syncIndexes();
  const removed = clearFolder(UPLOADS) + clearFolder(AUDIO_DIR) + clearFolder(CNIC_DIR);
  console.log(`Removed ${removed} uploaded / cached file(s).`);

  // ── Admin ──
  await createUser('admin', { name: 'Administrator', email: 'admin@carefirst.pk', password: process.env.ADMIN_PASSWORD || 'admin123', role: 'admin' });

  // ── Labs ──
  const week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  await createUser('chiniot', { name: 'Chiniot Diagnostics', email: 'lab.chiniot@carefirst.test', role: 'lab', phone: '0476-331122' });
  await LabProfile.create({
    user: users.chiniot._id, labName: 'Chiniot Diagnostics', location: 'Railway Road, Chiniot', licenseNumber: 'PHC-LAB-1021', phone: '0476-331122',
    bankDetails: { bankName: 'HBL', accountNumber: 'PK12HABB0001234567890123' }, jazzCash: '0301-7654321', easyPaisa: '0345-7654321',
    isCharityPartner: true, coordinates: { lat: 31.7200, lng: 72.9800 },
    tests: [
      { name: 'CBC', category: 'Haematology', price: 1200 },
      { name: 'Lipid Profile', category: 'Biochemistry', price: 2200 },
      { name: 'Liver Function Test', category: 'Biochemistry', price: 2500 },
      { name: 'Thyroid Profile', category: 'Endocrinology', price: 3500 },
      { name: 'MRI Brain', category: 'Radiology', price: 25000, installmentEnabled: true, installmentCount: 3, installmentTenureDays: 30 },
      { name: 'CT Scan Abdomen', category: 'Radiology', price: 18000, installmentEnabled: true, installmentCount: 2, installmentTenureDays: 30 },
    ],
  });

  await createUser('faisalabad', { name: 'Faisalabad City Lab', email: 'lab.faisalabad@carefirst.test', role: 'lab', phone: '041-2601234' });
  await LabProfile.create({
    user: users.faisalabad._id, labName: 'Faisalabad City Lab', location: 'Susan Road, Faisalabad', licenseNumber: 'PHC-LAB-2207', phone: '041-2601234',
    bankDetails: { bankName: 'Meezan Bank', accountNumber: 'PK36MEZN0009876543210987' }, jazzCash: '0300-1112233',
    coordinates: { lat: 31.4180, lng: 73.0790 },
    tests: [
      { name: 'CBC', category: 'Haematology', price: 900 },
      { name: 'Lipid Profile', category: 'Biochemistry', price: 1800 },
      { name: 'Liver Function Test', category: 'Biochemistry', price: 2000 },
      { name: 'Thyroid Profile', category: 'Endocrinology', price: 3000 },
      { name: 'Ultrasound Abdomen', category: 'Radiology', price: 3500 },
      { name: 'MRI Brain', category: 'Radiology', price: 22000, installmentEnabled: true, installmentCount: 4, installmentTenureDays: 30 },
    ],
  });

  // No map pin and no payment details — shows the lab warnings and blocked installments
  await createUser('jhang', { name: 'Jhang Medical Lab', email: 'lab.jhang@carefirst.test', role: 'lab', phone: '047-7623456' });
  await LabProfile.create({
    user: users.jhang._id, labName: 'Jhang Medical Lab', location: 'Civil Lines, Jhang', phone: '047-7623456',
    tests: [
      { name: 'CBC', category: 'Haematology', price: 800 },
      { name: 'MRI Brain', category: 'Radiology', price: 20000, installmentEnabled: true, installmentCount: 3, installmentTenureDays: 30 },
    ],
  });

  await createUser('labPending', { name: 'Sargodha Path Lab', email: 'lab.sargodha@carefirst.test', role: 'lab', status: 'pending' });
  await LabProfile.create({ user: users.labPending._id, labName: 'Sargodha Path Lab', location: 'University Road, Sargodha', licenseNumber: 'PHC-LAB-3310' });

  // ── Doctors ──
  const doctors = [
    { key: 'sara',  name: 'Dr. Sara Malik',  email: 'dr.sara@carefirst.test',  specialization: 'Cardiology', experience: 12, fee: 2000, duration: 20,
      days: week, slots: ['09:00 AM – 01:00 PM', '05:00 PM – 08:00 PM'], bio: 'Consultant cardiologist, Allied Hospital Faisalabad. Heart health, hypertension and chest pain.' },
    { key: 'ahmed', name: 'Dr. Ahmed Raza',  email: 'dr.ahmed@carefirst.test', specialization: 'General Physician', experience: 8, fee: 1000, duration: 15,
      days: week.slice(0, 5), slots: ['10:00 AM – 02:00 PM'], bio: 'Family physician in Chiniot — fever, infections, diabetes follow-ups.' },
    { key: 'hina',  name: 'Dr. Hina Qureshi', email: 'dr.hina@carefirst.test', specialization: 'Gynaecology', experience: 10, fee: 2500, duration: 30,
      days: ['Tuesday', 'Thursday', 'Saturday'], slots: ['04:00 PM – 07:00 PM'], bio: 'Gynaecologist and obstetrician with a focus on antenatal care.' },
  ];
  for (const d of doctors) {
    await createUser(d.key, { name: d.name, email: d.email, role: 'doctor', phone: '0300-0000000' });
    await DoctorProfile.create({
      user: users[d.key]._id, specialization: d.specialization, experience: d.experience, consultationFee: d.fee, consultationDuration: d.duration, bio: d.bio,
      availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        .map(day => ({ day, slots: d.days.includes(day) ? d.slots.map(time => ({ time })) : [] })),
    });
  }
  await createUser('docPending', { name: 'Dr. Kamran Ali', email: 'dr.kamran@carefirst.test', role: 'doctor', status: 'pending' });
  await DoctorProfile.create({ user: users.docPending._id, specialization: 'Dermatology', experience: 4 });

  // ── Lawyers ──
  await createUser('lawyer', { name: 'Adv. Tariq Shah', email: 'lawyer@carefirst.test', role: 'lawyer', phone: '0321-5556677' });
  await LawyerProfile.create({ user: users.lawyer._id, barNumber: 'LHC-4521', phone: '0321-5556677' });
  await createUser('lawyerPending', { name: 'Adv. Nadia Butt', email: 'lawyer.nadia@carefirst.test', role: 'lawyer', status: 'pending' });
  await LawyerProfile.create({ user: users.lawyerPending._id, barNumber: 'LHC-7788' });

  // ── Patients ──
  const patients = [
    { key: 'ayesha', name: 'Ayesha Khan',     cnic: '35202-1234567-1', city: 'Chiniot',    cnicStatus: 'verified' },
    { key: 'bilal',  name: 'Bilal Ahmed',     cnic: '33100-2345678-3', city: 'Faisalabad', cnicStatus: 'unverified' },
    { key: 'sana',   name: 'Sana Javed',      cnic: '33202-3456789-2', city: 'Jhang',      cnicStatus: 'rejected', cnicRejectionReason: 'The CNIC number does not match the name on NADRA records.' },
    { key: 'usman',  name: 'Usman Tariq',     cnic: '33103-4567890-5', city: 'Faisalabad', cnicStatus: 'unverified' },
    { key: 'fatima', name: 'Fatima Noor',     cnic: '35202-5678901-4', city: 'Chiniot',    cnicStatus: 'verified' },
    { key: 'hamza',  name: 'Hamza Ali',       cnic: '35201-6789012-7', city: 'Chiniot',    cnicStatus: 'verified' },
    { key: 'zainab', name: 'Zainab Bibi',     cnic: '33104-7890123-6', city: 'Faisalabad', cnicStatus: 'verified' },
    { key: 'imran',  name: 'Imran Hussain',   cnic: '35202-8901234-9', city: 'Chiniot',    cnicStatus: 'verified' },
    { key: 'rashid', name: 'Rashid Mehmood',  cnic: '33201-9012345-8', city: 'Jhang',      cnicStatus: 'verified' },
  ];
  for (const [i, p] of patients.entries()) {
    await createUser(p.key, { name: p.name, email: `${p.key}@carefirst.test`, role: 'patient', phone: `0300-55500${String(i + 1).padStart(2, '0')}` });
    await PatientProfile.create({
      user: users[p.key]._id, cnic: p.cnic, city: p.city, address: `House ${10 + i}, Main Bazaar, ${p.city}`,
      cnicStatus: p.cnicStatus, cnicRejectionReason: p.cnicRejectionReason,
      ...(p.cnicStatus !== 'unverified' && { cnicReviewedAt: daysAgo(3), cnicReviewedBy: users.admin._id }),
    });
  }

  // ── Appointments + prescriptions ──
  const sara = { fee: 2000, duration: 20 }, ahmed = { fee: 1000, duration: 15 }, hina = { fee: 2500, duration: 30 };
  const ayeshaVisit = await appointment({ patient: users.ayesha, doctor: users.sara, ...sara, status: 'completed', closedAt: daysAgo(1),
    startsAt: pktInstant(addDays(today, -1), '10:00') });
  await Prescription.create({
    patient: users.ayesha._id, doctor: users.sara._id, appointment: ayeshaVisit._id,
    tests: [{ testName: 'CBC', notes: 'Check haemoglobin' }, { testName: 'MRI Brain', notes: 'Recurring headaches for 3 months' }],
    generalNotes: 'Avoid heavy exercise until the MRI is done. Follow up after the results.',
  });
  await appointment({ patient: users.ayesha, doctor: users.ahmed, ...ahmed, startsAt: pktInstant(nextDateOn(week.slice(0, 5), 2), '11:00') });
  // Started half an hour ago and still open → the doctor can mark it completed / no-show and prescribe
  await appointment({ patient: users.bilal, doctor: users.sara, ...sara, startsAt: new Date(Math.floor((now.getTime() - 30 * 60000) / 60000) * 60000) });
  await appointment({ patient: users.usman, doctor: users.sara, ...sara, startsAt: pktInstant(nextDateOn(week, 1), '09:20') });
  await appointment({ patient: users.fatima, doctor: users.sara, ...sara, status: 'cancelled', cancelledBy: 'doctor', cancelledAt: daysAgo(1),
    cancellationReason: 'Clinic closed for a medical conference.', startsAt: pktInstant(nextDateOn(week, 1), '10:00') });
  await appointment({ patient: users.zainab, doctor: users.hina, ...hina, status: 'completed', closedAt: daysAgo(6),
    startsAt: pktInstant(addDays(today, -6), '16:30') });
  await appointment({ patient: users.imran, doctor: users.ahmed, ...ahmed, status: 'no_show', closedAt: daysAgo(3),
    startsAt: pktInstant(addDays(today, -3), '10:15') });

  // ── Installment plans in every state ──
  const g = (name, cnic, relation) => ({ name, cnic, phone: '0300-9876543', relation, address: 'House 5, Satellite Town, Chiniot' });

  // Usman: application waiting for admin review (CNIC not verified yet — the admin checks the pictures)
  const usmanPlan = await makePlan({ patientKey: 'usman', labKey: 'chiniot', testName: 'MRI Brain', state: 'pending_approval', approvedDaysAgo: 0,
    guarantor: g('Tariq Mehmood', '33103-1112223-1', 'Father') });
  await usmanPlan.wallet.save();

  // Fatima: approved, service fee screenshot uploaded → admin verifies to activate
  const fatimaPlan = await makePlan({ patientKey: 'fatima', labKey: 'faisalabad', testName: 'MRI Brain', state: 'awaiting_fee', approvedDaysAgo: 1,
    guarantor: g('Noor Ahmed', '35202-2223334-3', 'Husband') });
  fatimaPlan.wallet.serviceFee.receiptUrl = receipt('Fatima Noor', 'CareFirst service fee', SERVICE_FEE, 'CareFirst');
  fatimaPlan.wallet.serviceFee.receiptUploadedAt = daysAgo(0);
  await fatimaPlan.wallet.save();

  // Hamza: active, down payment receipt uploaded → lab confirms → admin verifies; installment #1 due in 3 days
  const hamzaPlan = await makePlan({ patientKey: 'hamza', labKey: 'chiniot', testName: 'CT Scan Abdomen', state: 'active', approvedDaysAgo: 28, activatedDaysAgo: 27,
    guarantor: g('Ali Raza', '35201-3334445-5', 'Brother') });
  hamzaPlan.wallet.downPayment.receiptUrl = receipt('Hamza Ali', 'Down payment', hamzaPlan.wallet.downPayment.amount, 'Chiniot Diagnostics');
  hamzaPlan.wallet.downPayment.receiptUploadedAt = daysAgo(1);
  await hamzaPlan.wallet.save();

  // Zainab: active, down payment verified, installment #1 confirmed by the lab → admin verifies
  const zainabPlan = await makePlan({ patientKey: 'zainab', labKey: 'faisalabad', testName: 'MRI Brain', state: 'active', approvedDaysAgo: 26, activatedDaysAgo: 25,
    guarantor: g('Bashir Ahmed', '33104-4445556-7', 'Father') });
  Object.assign(zainabPlan.wallet.downPayment, {
    receiptUrl: receipt('Zainab Bibi', 'Down payment', zainabPlan.wallet.downPayment.amount, 'Faisalabad City Lab'),
    receiptUploadedAt: daysAgo(24), labApproved: true, labApprovedAt: daysAgo(24), adminVerified: true, adminVerifiedAt: daysAgo(23), adminVerifiedBy: users.admin._id,
  });
  Object.assign(zainabPlan.wallet.installments[0], {
    receiptUrl: receipt('Zainab Bibi', 'Installment 1', zainabPlan.wallet.installments[0].amount, 'Faisalabad City Lab'),
    receiptUploadedAt: daysAgo(2), labApproved: true, labApprovedAt: daysAgo(1),
  });
  await zainabPlan.wallet.save();

  // Imran: missed installment #1 → defaulter, case with the lawyer
  const imranPlan = await makePlan({ patientKey: 'imran', labKey: 'chiniot', testName: 'MRI Brain', state: 'active', approvedDaysAgo: 44, activatedDaysAgo: 43,
    guarantor: g('Hussain Bakhsh', '35202-5556667-9', 'Father') });
  Object.assign(imranPlan.wallet.downPayment, {
    receiptUrl: receipt('Imran Hussain', 'Down payment', imranPlan.wallet.downPayment.amount, 'Chiniot Diagnostics'),
    receiptUploadedAt: daysAgo(42), labApproved: true, labApprovedAt: daysAgo(42), adminVerified: true, adminVerifiedAt: daysAgo(41), adminVerifiedBy: users.admin._id,
  });
  imranPlan.wallet.installments[0].status = 'overdue';
  imranPlan.wallet.status = 'defaulter';
  await imranPlan.wallet.save();
  const missed = imranPlan.wallet.installments[0];
  const escalatedAt = new Date(missed.dueDate.getTime() + (GRACE_DAYS + 1) * DAY);
  const imranCase = await DefaulterCase.create({
    patient: users.imran._id, wallet: imranPlan.wallet._id, assignedLawyer: users.lawyer._id,
    missedInstallments: 1, totalOverdue: missed.amount, escalatedAt,
    legalAgreementText: generateLegalAgreement({
      patient: users.imran, patientCnic: imranPlan.wallet.patientCnic, patientAddress: imranPlan.wallet.patientAddress,
      guarantor: imranPlan.wallet.guarantor, hasCnicPictures: true, testName: imranPlan.wallet.testName,
      totalAmount: imranPlan.wallet.totalAmount, remainingBalance: imranPlan.wallet.remainingBalance, escalatedAt,
    }),
  });

  // ── Lab visits + reports ──
  const testId = async (labKey, name) => (await LabProfile.findOne({ user: users[labKey]._id })).tests.find(t => t.name === name);

  // Ayesha: a completed CBC with a report, English + Urdu summary (listen in My Reports)
  const fslCbc = await testId('faisalabad', 'CBC');
  const ayeshaBooking = await LabBooking.create({
    patient: users.ayesha._id, lab: users.faisalabad._id, labTest: fslCbc._id, testName: 'CBC', price: fslCbc.price,
    visitDate: addDays(today, -6), status: 'completed', sampleCollectedAt: daysAgo(6), completedAt: daysAgo(5),
  });
  const ayeshaReport = await TestReport.create({
    patient: users.ayesha._id, lab: users.faisalabad._id, testName: 'CBC', booking: ayeshaBooking._id,
    reportUrl: saveFile('reports', 'CBC report - Ayesha Khan', ['Haemoglobin: 11.2 g/dL (slightly low)', 'WBC: 7,400 /uL (normal)', 'Platelets: 250,000 /uL (normal)', 'Lab: Faisalabad City Lab']),
    notes: 'Sample collected 9:30 AM',
    summary: 'Your blood count is mostly normal. Haemoglobin is slightly low, so please discuss iron-rich food or supplements with your doctor.',
    summaryUrdu: 'آپ کے خون کا ٹیسٹ زیادہ تر نارمل ہے۔ ہیموگلوبن تھوڑا کم ہے، اس لیے آئرن والی غذا یا سپلیمنٹ کے بارے میں اپنے ڈاکٹر سے مشورہ کریں۔',
    summaryUrduSource: 'lab', summaryUrduEditedAt: daysAgo(5), summarySource: 'lab',
    // What the automatic reader found in the file (decision 9)
    autoRead: {
      status: 'ready', kind: 'table', pages: 1, totalPages: 1, readAt: daysAgo(5),
      findings: [
        { name: 'Haemoglobin', result: '11.2', unit: 'g/dL', range: '12 - 16', normalLow: 12, normalHigh: 16, status: 'low', basis: 'range' },
        { name: 'WBC', result: '7,400', unit: '/uL', range: '4,000 - 11,000', normalLow: 4000, normalHigh: 11000, status: 'normal', basis: 'range' },
        { name: 'Platelets', result: '250,000', unit: '/uL', range: '150,000 - 400,000', normalLow: 150000, normalHigh: 400000, status: 'normal', basis: 'range' },
      ],
    },
  });
  ayeshaBooking.report = ayeshaReport._id;
  await ayeshaBooking.save();

  // Hamza: CT scan paid through his plan, sample collected → the lab uploads the report
  const ct = await testId('chiniot', 'CT Scan Abdomen');
  await LabBooking.create({
    patient: users.hamza._id, lab: users.chiniot._id, labTest: ct._id, testName: 'CT Scan Abdomen', price: ct.price,
    visitDate: addDays(today, -1), paymentMethod: 'installment', wallet: hamzaPlan.wallet._id, status: 'sample_collected', sampleCollectedAt: daysAgo(1),
  });

  // Zainab: CBC visit today, not collected yet → the lab marks the sample collected
  const chnCbc = await testId('chiniot', 'CBC');
  await LabBooking.create({
    patient: users.zainab._id, lab: users.chiniot._id, labTest: chnCbc._id, testName: 'CBC', price: chnCbc.price, visitDate: today,
  });

  // ── Community support ──
  const rashidApp = await CommunityApplication.create({
    patient: users.rashid._id, testRequired: 'MRI Brain',
    documents: [
      saveFile('community-docs', 'Electricity bill - Rashid Mehmood', ['FESCO bill, units used: 85', 'Amount: PKR 1,950']),
      saveFile('community-docs', 'Bank statement - Rashid Mehmood', ['Average monthly balance: PKR 6,200', 'Monthly income: PKR 22,000 (daily wage)']),
    ],
  });
  const zainabApp = await CommunityApplication.create({
    patient: users.zainab._id, testRequired: 'Thyroid Profile', status: 'approved', assignedLab: users.chiniot._id,
    documents: [saveFile('community-docs', 'Utility bill - Zainab Bibi', ['Gas bill: PKR 1,100'])],
    slip: { slipId: 'SLP-' + String(Date.now()).slice(-6), generatedAt: daysAgo(2) }, reviewedAt: daysAgo(2), reviewedBy: users.admin._id,
  });

  // ── A few notifications so every inbox has something ──
  await notify(users.admin, 'plan_submitted', 'New Installment Plan Application', 'Usman Tariq applied to pay for MRI Brain at Chiniot Diagnostics in installments.', { walletId: usmanPlan.wallet._id });
  await notify(users.admin, 'service_fee_uploaded', 'Service Fee Receipt Uploaded', `Fatima Noor uploaded the PKR ${SERVICE_FEE} service fee receipt for the MRI Brain plan.`, { walletId: fatimaPlan.wallet._id });
  await notify(users.admin, 'receipt_lab_approved', 'Receipt Ready for Verification', 'Lab confirmed receipt for Zainab Bibi — installment #1. Please verify.', { walletId: zainabPlan.wallet._id });
  await notify(users.admin, 'community_submitted', 'New Community Support Application', 'Rashid Mehmood applied for community support for "MRI Brain".', { applicationId: rashidApp._id });
  await notify(users.chiniot, 'receipt_uploaded', 'New Payment Receipt', 'Hamza Ali uploaded a receipt for the down payment — CT Scan Abdomen. Please confirm you received the payment.', { walletId: hamzaPlan.wallet._id, payment: 'down_payment' });
  await notify(users.chiniot, 'lab_booking_created', 'New Test Booking', `Zainab Bibi booked CBC for today (PKR ${chnCbc.price.toLocaleString()}, to be paid at the lab).`);
  await notify(users.lawyer, 'defaulter_escalated', 'New Defaulter Case Assigned', `Imran Hussain missed installment #1 — PKR ${missed.amount.toLocaleString()} overdue.`, { caseId: imranCase._id });
  await notify(users.ayesha, 'prescription_issued', 'New Prescription Issued', 'Dr. Sara Malik prescribed CBC and MRI Brain. Use "Find labs" in My Reports to book them.');
  await notify(users.ayesha, 'test_report_uploaded', 'Test Report Ready', 'Your CBC report from Faisalabad City Lab is ready, with an Urdu summary you can listen to.');
  await notify(users.sana, 'cnic_rejected', 'CNIC Not Verified', 'The CNIC number does not match the name on NADRA records. Please correct your CNIC from your profile.');
  await notify(users.zainab, 'community_approved', 'Community Support Approved', `Your community support application has been approved. Slip ID: ${zainabApp.slip.slipId}.`);

  // ── Summary ──
  const row = (who, login, what) => console.log(`  ${who.padEnd(24)} ${login.padEnd(34)} ${what}`);
  console.log(`\nSeeded "${dbName}". Password for every demo account: ${PASSWORD}`);
  console.log(`Admin: log in with username "${process.env.ADMIN_USERNAME || 'admin'}" and ADMIN_PASSWORD from .env\n`);
  row('PATIENTS', '', '');
  row('Ayesha Khan', 'ayesha@carefirst.test', 'clean start: prescription (CBC, MRI) → Find labs, True Cost, apply, book; report with Urdu summary');
  row('Bilal Ahmed', 'bilal@carefirst.test', 'CNIC unverified (admin verifies); appointment with Dr. Sara in progress');
  row('Sana Javed', 'sana@carefirst.test', 'CNIC rejected — correct it in Profile');
  row('Usman Tariq', 'usman@carefirst.test', 'installment application under review (CNIC not verified yet: approving it verifies the CNIC); appointment tomorrow');
  row('Fatima Noor', 'fatima@carefirst.test', 'plan approved, fee screenshot uploaded; appointment cancelled by doctor');
  row('Hamza Ali', 'hamza@carefirst.test', 'active plan: down payment awaiting lab; CT scan sample collected; installment due in 3 days');
  row('Zainab Bibi', 'zainab@carefirst.test', 'active plan: installment #1 awaiting admin; CBC visit today; community slip approved');
  row('Imran Hussain', 'imran@carefirst.test', 'defaulter — case with the lawyer');
  row('Rashid Mehmood', 'rashid@carefirst.test', 'community support application pending');
  row('DOCTORS', '', '');
  row('Dr. Sara Malik', 'dr.sara@carefirst.test', 'Cardiology · Mon–Sat 9–1 & 5–8 · 20 min');
  row('Dr. Ahmed Raza', 'dr.ahmed@carefirst.test', 'General Physician · Mon–Fri 10–2 · 15 min');
  row('Dr. Hina Qureshi', 'dr.hina@carefirst.test', 'Gynaecology · Tue/Thu/Sat 4–7 · 30 min');
  row('LABS', '', '');
  row('Chiniot Diagnostics', 'lab.chiniot@carefirst.test', 'pin + payment set; charity partner; Hamza / Zainab work waiting');
  row('Faisalabad City Lab', 'lab.faisalabad@carefirst.test', 'pin + payment set; cheaper but ~35 km from Chiniot');
  row('Jhang Medical Lab', 'lab.jhang@carefirst.test', 'NO pin, NO payment details (warnings, installments blocked)');
  row('LAWYER', 'lawyer@carefirst.test', 'Adv. Tariq Shah — Imran\'s defaulter case');
  row('PENDING (admin approves)', 'dr.kamran@ / lab.sargodha@ / lawyer.nadia@ (carefirst.test)', '');
  await mongoose.disconnect();
};

seed().catch(async (err) => {
  console.error('Seed failed:', err);
  await mongoose.disconnect();
  process.exit(1);
});
